name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag, and push Docker image
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      - 
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   
      
      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache  
          tags: ${{ steps.meta.outputs.tags }}

      # Install Docker Scout
      - 
        name: Install Docker Scout
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          docker scout --version

      # Analyze Docker image with Docker Scout
      - 
        name: Analyze Docker image for vulnerabilities
        id: scan
        run: |
          docker scout cves ${{ vars.DOCKERHUB_USERNAME }}/example:${{ steps.meta.outputs.tags | split(',')[0] }} > scout-report.txt
          CRITICAL_COUNT=$(grep "CRITICAL" scout-report.txt | wc -l)
          HIGH_COUNT=$(grep "HIGH" scout-report.txt | wc -l)
          echo "CRITICAL_COUNT=${CRITICAL_COUNT}" >> $GITHUB_ENV
          echo "HIGH_COUNT=${HIGH_COUNT}" >> $GITHUB_ENV

      # Push to GHCR only if no critical or high vulnerabilities
      - 
        name: Login to GitHub Container Registry
        if: ${{ env.CRITICAL_COUNT == 0 && env.HIGH_COUNT == 0 }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - 
        name: Push Docker image to GHCR
        if: ${{ env.CRITICAL_COUNT == 0 && env.HIGH_COUNT == 0 }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/example:latest
            ghcr.io/${{ github.repository }}/example:${{ steps.meta.outputs.tags }}
